Maintenance 09 2024
MITLibraries/browsertrix-harvester pull request #39
Opened 2024-09-11 14:20 UTC by ehanson8

### Purpose and background context
Updates app according to our [maintenance week documentation](https://mitlibraries.atlassian.net/wiki/spaces/IN/pages/3445948428/DataEng+Application+Maintenance).

### How can a reviewer manually see the effects of these changes?
Run `make test` and `make lint` to confirm they still pass

### Includes new or updated dependencies?
YES

### Changes expectations for external applications?
NO

### Developer
- [x] All new ENV is documented in README
- [x] All new ENV has been added to staging and production environments
- [x] All related Jira tickets are linked in commit message(s)
- [x] Stakeholder approval has been confirmed (or is not needed)

### Code Reviewer(s)
- [ ] The commit message is clear and follows our guidelines (not just this PR message)
- [ ] There are appropriate tests covering any new functionality
- [ ] The provided documentation is sufficient for understanding any new functionality introduced
- [ ] Any manual tests have been performed **or** provided examples verified
- [ ] New dependencies are appropriate or there were no changes

2024-09-11 15:23 UTC, ghukill requested changes
Before diving into the rest of the PR (which looks great at a glance, not anticipating any requests), did have one.

While attempting to run a local harvest test via:
```shell
```

It was discovered that the [testing configurations here](https://github.com/MITLibraries/browsertrix-harvester/blob/maintenance-09-2024/tests/fixtures/lib-website-homepage.yaml) are pointing at a version of the website no longer available.

A more stable version was shared, which would allow updating that YAML to the following:

```yaml
generateCDX: true
generateWACZ: true
text: to-pages
# prevent PAGES from getting crawled; scoping
exclude:
  - ".*lib.mit.edu/search/.*"
  - ".*mit.primo.exlibrisgroup.com/.*"
# prevent RESOURCES / ASSETS from getting retrieved; URL requests
blockRules:
  - ".*googlevideo.com.*"
  - ".*cdn.libraries.mit.edu/media/.*"
  - "\\.(jpg|png)$"
depth: 1
maxPageLimit: 20
timeout: 30
scopeType: "domain"
seeds:
  - url: https://www-test.libraries.mit.edu/sitemap.xml
    sitemap: https://www-test.libraries.mit.edu/sitemap.xml
```

Can we make this change?  Thanks!

2024-09-11 15:46 UTC, ehanson8 commented
@ghukill Good catch, made the change!

2024-09-11 17:14 UTC, ghukill approved these changes
Approved!  Able to run a local crawl/harvest, all looks good.

2024-09-20 13:27 UTC, jonavellecuerdo approved these changes

2024-09-20 14:16 UTC, merged